version: "3"
services:
    node:
        container_name: restaurant_reservations_app
        build: .
        ports:
            - 3000:3000
        volumes:
            - ./:/server
        depends_on:
            - mysql
    mysql:
        container_name: restaurant_reservations_db
        image: mysql:5.7
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_NAME}
            # MYSQL_USER: ${DB_USER}
            # MYSQL_PASSWORD: ${DB_PASS}
volumes:
    db-data: {}
